### ISSUE TITLE
corpus*.yml does not load out of the box

### ISSUE THREAD

**Issue by yveshwang** [RocketChat/hubot-natural#25]
using node `v6.10.3`
Note that the cat example works fine. i was playing around how to get `next` and `interactions` working to see if we can chain some responses via some notion of context. (not sure if i quite get thats the correct usage.) none the less, had some issue with loading these yaml files.

the following errors are recorded when attempting to load `corpus.yml` and `corpus-v1.yml`

```
Tue Dec 12 2017 11:09:57 GMT+0100 (CET)] ERROR Unable to load /Users/yveshwang/github/hubot-natural/scripts/index: TypeError: Cannot read property 'find' of undefined
    at classifyInteraction (/Users/yveshwang/github/hubot-natural/scripts/bot/index.coffee:83:46)
    at global.train (/Users/yveshwang/github/hubot-natural/scripts/bot/index.coffee:177:9)
    at module.exports (/Users/yveshwang/github/hubot-natural/scripts/bot/index.coffee:183:10)
    at Robot.loadFile (/Users/yveshwang/github/hubot-natural/node_modules/hubot/src/robot.coffee:358:11)
    at Robot.load (/Users/yveshwang/github/hubot-natural/node_modules/hubot/src/robot.coffee:377:10)
    at RocketChatBotAdapter.loadScripts (/Users/yveshwang/github/hubot-natural/node_modules/hubot/bin/hubot:97:13)
    at RocketChatBotAdapter.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at RocketChatBotAdapter.emit (events.js:185:7)
    at /Users/yveshwang/github/hubot-natural/node_modules/hubot-rocketchat/src/rocketchat.coffee:212:6
    at _fulfilled (/Users/yveshwang/github/hubot-natural/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/yveshwang/github/hubot-natural/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/yveshwang/github/hubot-natural/node_modules/q/q.js:816:13)
    at /Users/yveshwang/github/hubot-natural/node_modules/q/q.js:624:44
    at runSingle (/Users/yveshwang/github/hubot-natural/node_modules/q/q.js:137:13)
    at flush (/Users/yveshwang/github/hubot-natural/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

slightly diff error for `corpus-sei.yml`

```
[Tue Dec 12 2017 11:10:07 GMT+0100 (CET)] ERROR Unable to load /Users/yveshwang/github/hubot-natural/scripts/index: TypeError: Cannot read property 'substr' of undefined
    at global.train (/Users/yveshwang/github/hubot-natural/scripts/bot/index.coffee:174:14)
    at module.exports (/Users/yveshwang/github/hubot-natural/scripts/bot/index.coffee:183:10)
    at Robot.loadFile (/Users/yveshwang/github/hubot-natural/node_modules/hubot/src/robot.coffee:358:11)
    at Robot.load (/Users/yveshwang/github/hubot-natural/node_modules/hubot/src/robot.coffee:377:10)
    at RocketChatBotAdapter.loadScripts (/Users/yveshwang/github/hubot-natural/node_modules/hubot/bin/hubot:97:13)
    at RocketChatBotAdapter.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at RocketChatBotAdapter.emit (events.js:185:7)
    at /Users/yveshwang/github/hubot-natural/node_modules/hubot-rocketchat/src/rocketchat.coffee:212:6
    at _fulfilled (/Users/yveshwang/github/hubot-natural/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/yveshwang/github/hubot-natural/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/yveshwang/github/hubot-natural/node_modules/q/q.js:816:13)
    at /Users/yveshwang/github/hubot-natural/node_modules/q/q.js:624:44
    at runSingle (/Users/yveshwang/github/hubot-natural/node_modules/q/q.js:137:13)
    at flush (/Users/yveshwang/github/hubot-natural/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by diegodorgam** [comment]
fixed @yveshwang 
there actually was a line calling for `config` that now goes by `global.config`.
You can try again please
