### ISSUE TITLE
Bot not answering in public and private groups

### ISSUE THREAD

**Issue by richieri** [RocketChat/hubot-natural#42]
Got following error, saying res is not defined

[Thu Mar 29 2018 14:58:19 GMT+0000 (UTC)] ERROR ReferenceError: res is not defined
    at createMatch (/home/hubotnat/bot/scripts/bot/index.coffee:40:3)
    at TextListener.callback (/home/hubotnat/bot/scripts/bot/index.coffee:64:11)
    at /home/hubotnat/bot/node_modules/hubot/src/listener.coffee:65:12
    at allDone (/home/hubotnat/bot/node_modules/hubot/src/middleware.coffee:44:37)
    at /home/hubotnat/bot/node_modules/async/lib/async.js:274:13
    at Object.async.eachSeries (/home/hubotnat/bot/node_modules/async/lib/async.js:142:20)
    at Object.async.reduce (/home/hubotnat/bot/node_modules/async/lib/async.js:268:15)
    at /home/hubotnat/bot/node_modules/hubot/src/middleware.coffee:49:13
    at process._tickCallback (internal/process/next_tick.js:112:11)

**Comment by diegodorgam** [comment]
can I close this @richieri ?

**Comment by richieri** [comment]
Yes, sorry, I haven't seen the last message :/

Em qua, 2 de mai de 2018 00:31, Diego Dorgam <notifications@github.com>
escreveu:
