### ISSUE TITLE
ENOENT: no such file or directory, lstat 'corpus.yml'

### ISSUE THREAD

**Issue by krishnaprasadhg** [RocketChat/hubot-natural#56]
bin\hubot
npm WARN hubot-help@0.2.2 requires a peer of coffee-script@^1.12.6 but none is installed. You must install peer dependencies yourself.

up to date in 6.152s
[Mon Mar 25 2019 17:44:38 GMT+0530 (India Standard Time)] DEBUG Loading adapter rocketchat
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] INFO Starting Rocketchat adapter version 1.0.12...
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] INFO Once connected to rooms I will respond to the name: ServiceDesk
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] WARNING No services ROCKETCHAT_ROOM provided to Hubot, using
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] INFO Connecting To: localhost:3000
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] INFO Successfully connected!
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] INFO
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] INFO Logging In
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] INFO Successfully Logged In
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] INFO rid:  []
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] INFO All rooms joined.
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] INFO Preparing Meteor Subscriptions..
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] INFO Subscribing to Room: __my_messages__
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] INFO Successfully subscribed to messages
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] INFO Setting up reactive message list...
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] DEBUG Loading scripts from D:\BT\Rocket.Chat\RC\mybot\scripts
[Mon Mar 25 2019 17:44:39 GMT+0530 (India Standard Time)] DEBUG Parsing help for D:\BT\Rocket.Chat\RC\mybot\scripts\example.coffee
Loading corpus: corpus.yml
An error occurred while trying to load bot's config.
{ Error: ENOENT: no such file or directory, lstat 'corpus.yml'
    at Object.lstatSync (fs.js:840:3)
    at common.loadConfigfile (D:\BT\Rocket.Chat\RC\mybot\scripts\lib\common.coffee:72:11)
    at Object.<anonymous> (D:\BT\Rocket.Chat\RC\mybot\scripts\index.coffee:7:19)
    at Object.<anonymous> (D:\BT\Rocket.Chat\RC\mybot\scripts\index.coffee:1:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.loadFile (D:\BT\Rocket.Chat\RC\mybot\node_modules\coffeescript\lib\coffee-script\register.js:16:19)
    at Module.load (D:\BT\Rocket.Chat\RC\mybot\node_modules\coffeescript\lib\coffee-script\register.js:45:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Robot.loadFile (D:\BT\Rocket.Chat\RC\mybot\node_modules\hubot\src\robot.coffee:355:18)
    at Robot.load (D:\BT\Rocket.Chat\RC\mybot\node_modules\hubot\src\robot.coffee:377:10)
    at RocketChatBotAdapter.loadScripts (D:\BT\Rocket.Chat\RC\mybot\node_modules\hubot\bin\hubot:93:11)
    at Object.onceWrapper (events.js:277:13)
    at RocketChatBotAdapter.emit (events.js:189:13)
    at D:\BT\Rocket.Chat\RC\mybot\node_modules\hubot-rocketchat\src\rocketchat.coffee:212:6
    at _fulfilled (D:\BT\Rocket.Chat\RC\mybot\node_modules\q\q.js:854:54)
    at D:\BT\Rocket.Chat\RC\mybot\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (D:\BT\Rocket.Chat\RC\mybot\node_modules\q\q.js:816:13)
    at D:\BT\Rocket.Chat\RC\mybot\node_modules\q\q.js:624:44
    at runSingle (D:\BT\Rocket.Chat\RC\mybot\node_modules\q\q.js:137:13)
    at flush (D:\BT\Rocket.Chat\RC\mybot\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)

  errno: -4058,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'corpus.yml' }

**Comment by bwbw723** [comment]
@krishnaprasadhg I have met the same error when using the default configurations on HUBOT_CORPUS, after replacing it with full path, I have started the bot. Please just have a try.
